### PR TITLE
Pokemon Script Potential Additions

### PR DESCRIPTION
**Pull request by bradjrenshaw**
While I was playing through Pokemon Crystal I noticed a few areas of the game where certain additions would make game play easier. I kind of added these changes as I went along.

I added the map viewer component due to the Ice Path area. It allows for the viewing of the tiles around you. I added certain objects to the list, for example trees, holes and whirlpools. Ocean tiles now play an ocean swim sound on movement.
there is now a feature (toggle-able with i) to announce tile changes as you move. I found this made navigation a lot easier.

### CODE REVIEW

**Comment by tspivey** [comment]
Great start. Some observations:
1. The tiles are announced as numbers. This isn't as useful as it could be; see this page:
for a bit better data.
http://hax.iimarck.us/topic/1378/
2. If you can, squash/rebase a lot of the minor bugfix commits; this makes a cleaner history. Google should turn it up, then you can update the pull request a bit.

**Comment by bradjrenshaw** [comment]
I have made a number of the changes you suggested. I was wondering a few things.

How would you recommend unknown tiles to be handled? As of now it just returns the tile id if it isn't in the list of tile names, but I'm wondering if there's any preference you would have on the matter.

Would you possibly want to add some kind of filter to the objects list? right now all it does is list everything, but maybe there could be something to switch between whether it showed only objects, only connections, only certain types of terrain objects (trees, etc).

**Comment by tspivey** [comment]
Currently, j/k/l are previous/current/next object. I was thinking that shift j and shift l would move you to the previous/next object of a different type, wrapping if needed.
Would that work?
As to unknown tiles, I'm not sure what to do with those yet. Can we find out what the ids are for?
Also, squash your commits into a few useful ones. See:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by bradjrenshaw** [comment]
I already used shift u, i, p, j, k and l for the map viewer. I was wondering about using u and o for the type cycling.

I'm running into a problem. The footstep function is called before the coordinate values are written to the piece of memory the script uses but after the collision values are set. I'm not really sure what to do about fixing it, since different language roms use different ram locations. I was planning on making the script announce objects directly above, below, to the left or to the right of the player, etc.

**Comment by tspivey** [comment]
u and o would be fine.
What memory location are you trying to use? Look at the location of the 
footstep function (0x292c in the english rom, I think) and see if you 
can go forward a few instructions.

**Comment by bradjrenshaw** [comment]
I have made a few additions and changes as you can see. For some reason when I pushed after rebasing it did not display the rebased commits properly with the pull request.

I was wondering what tools you used to view the rom instructions however as I am somewhat knew to this.

**Comment by bradjrenshaw** [comment]
Do you have any particular comments for this code? I notice the thread has gone rather silent and wanted your input on the previous comment before continuing.

**Comment by tspivey** [comment]
Sorry. With the recent changes merged in (camera and such), I haven't
had a chance to look at this yet.
Viewing the rom instructions; vba has a disassembler if I know where I'm
going, but the main source is the already existing disassembly.
https://github.com/kanzure/pokecrystal

**Pull request closed without merging**
